
Arrow-like characters in Unicode:

    Leftwards Arrow: ← &#x2190;
    Upwards Arrow: ↑ &#x2191;
    Rightwards Arrow: → &#x2192;
    Downwards Arrow: ↓ &#x2193;
    Diagonal Arrow: ↗ &#x2197;
    Diagonal Arrow: ↘ &#x2198;
    Bent Arrow: ↪ &#x21AA;
    Bent Arrow: ↩ &#x21A9;


::: {.rmdcaution}
RED BOX Example of an **.rmdcaution** block.

:::

::: {.rmdimportant}
GREEN BOX Example of an **.rmdimportant** block.

:::

::: {.rmdtip}
BLUE BOX Example of an **.rmdtip** block.

:::

::: {.rmdwarning}
BLUEVIOLET BOX Example of an **.rmdwarning** block.

:::



# Preface {-}

<blockquote class="my-quote">
  <p><strong>"The harder I work, the luckier I get."</strong></p>
  <p class="quote-author">          — Lee Trevino</p>
  <p class="quote-description">(one of the greatest professional golfers of all time)</p>
</blockquote>


Welcome to the first edition of __[*Reimagine Your Business, A Personalized Guide to Beating Your Competition* (Swart 2023)]()__.. 

After 40 years of helping people who run companies, this book is my attempt to pass on what I've learned so you can know at least one way to make your business ***exceptional,*** and reap the rewards that come with that.  There's more than one way to make money in this world, and all of them require some measure of luck to succeed.  

<blockquote class="my-box" style="text-align: center;">
<p>
    <span style="font-size: 14px">MOTIVATION</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px">ASPIRATION</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px">CREATE VALUE</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">COMPETITIVE STRATEGY </span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">MARKET TACTICS</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">PHILOSOPHY</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">OPERATIONS</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">CUSTOMERS</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">SOME LUCK</span>
    <span style="font-size: 24px;">=</span>
    <strong><span style="color: green; font-size: 20px">SUCCESS</span></strong>
  </p>
</blockquote>  


This diagram is not a statement of deductive logic.  You don't have to do these things in order.  It is a useful aid to learning and it appears as an orientation marker in each chapter.


This book is about the 'non-luck' part of the equation.  It is about what you can do for yourself and your business to make your own 'luck'.

Taking your company to the next level requires reimagining your company as ever more effective at delivering value (from your customer's point of view).  Management is too often persuaded to focus solely on what their employees are doing, with scant attention to the rules of thumb that make up the system the world encounters when doing business with them.


## The Power of Rules of Thumb

A rule of thumb is a practical guideline used to make approximate judgments or decisions. It's a rough, often simple principle that is not intended to be precise but provides a quick and easy way to approach a problem or situation.

Examples: "A good rule of thumb is to save 10% of your income for retirement." or "As a rule of thumb, add 15 minutes to your travel time to account for traffic."

People crave rules of thumb.  They are one way we mentally and emotionally manage the complexity of running a business.  They are powerful things.  The following simple rule of thumb helps power a company with revenues of about $700 million (US).  (When you see an arrow, say the word 'make' in your head)

<div align="center">

**DELIGHTED EMPLOYEES <span style="font-size: 24px;">&#x2192;</span> DELIGHTED CUSTOMERS <span style="font-size: 24px;">&#x2192;</span> DELIGHTED BANKER <span style="font-size: 24px;">&#x2192;</span> DELIGHTED OWNER!**

</div>


Breathing life into that rule of thumb was a significant challenge. It required determination and boldness to translate it into 'the way we do business here'.

Some owners do this almost by 'instinct.'  They seem to have a natural knack for it and develop rules of thumb for themselves that really set them apart.  The rest of us (hopefully!) learn by trial and error.

This book is here to help you create rules of thumb that are specific to you; that can take you and your company to the next level.

Companies with inadequate or incompatable rules of thumb are those most likely to struggle or fail.  This observation was a strong motivation for me to create this book.

Good rules of thumb are like ingredients in a recipe.  It's up to you as the 'chef' to combine them in appropriate and creative ways.  A great chef knows the characteristics of each ingredient and how the ingredients interact with each other under varying conditions.  Expert chefs don't need recipes.  They find joy in experimenting with ingredients and combinations.  The marketplace often rewards creative courage like that.  


Although I discuss several approaches, the book is really about one particular way to maximize your opportunities in business.  A combination of ideas that you can incorporate immeddiately into rules of thumb to make your business unique.

Being VERY special is one of the best ways for any company to succeed.  <span style="color: green; font-size: 18px;"><b>However, most owners do not realize just how special you have to be to beat the competition.<b></span>  

<span style="color: royalblue; font-size: 18px;"><b><i>And, that's where the opportunities lie!<b><i></span>


Hopefully, the book makes learning as quick and painless as possible.  I'm confident it will help you avoid some mistakes and teach you useful concepts, tools, and techniques to attack many types of problems.

It should help both the new business owner and the seasoned owner beat their competition.  You will learn why some companies enjoy almost unbelievable success while others just exist (its not just luck).  

My aim is to explain in plain language, and with examples, the actions the marketplace rewards and those it punishes.  Learn why it works the way it does and how to make it work for you.  I want you to beat the poor survival rates companies face and leap ahead of your competitors.


I had four main goals when writing this book:


1. Create awareness of the interactions between your motivations, marketplace needs, and the rules of thumb you currently use.  The aim is to improve them or replace them with better ones.  Removing contradictory rules of thumb should be a prime objective for all owners

1. Create awareness of how conventional rules of thumb about marketing, operating, and managing your company will <span style="color: red; font-weight: 900;">NOT</span> raise you above your competition.  In fact, they are holding you back.  

    Part I is also intended to awaken your mind to the practical need to get moving **NOW** to gain a new and better position in the marketplace.


1. Provide inspirational examples of ordinary people achieving extraordinary results by using straightforward rules of thumb and taking them very, very seriously in their planning and day-to-day operations.

    Part II illustrates how the marketplace can richly reward thoughtful and adventurous rules of thumb that differentiate you.


1. Examine in detail how new, improved rules of thumb in various areas of your business can elevate your company to new levels of success.  Practicallity and consistency are the aims.  

    I love the power of quotations, maxims, aphorisims, and analogies. They convey a lot with memerable simplicity and clarity.  The book is full of them.

    Part III is for those with the ambition, creative courage, and sense of urgency required to reimagine their current way of doing business and move to the next level of competition.


The principles put forth are timeless, practical, and deceptively straightforward.  The willingness to use this system to your advantage comes from you.  For those who make a full commitment it's a sure-fire way to bring you more of what you want.


## Who the Book is For

The book is for those with ambition (however modest), a willingness to try new things, and a sense of urgency.  Succeeding is about being effective, not just efficient.  It is about knowing your purpose in the marketplace as well as you know your product.  This book is for all who want to sharpen their management skills, better understand the marketplace in which they operate, and improve their competitive position.


## Who the Book is <b>NOT<b> For

The book will not help you if your primary objective for having a business is to avoid working under a boss, to work in your pajamas, or to turn your pleasurable hobby into a little side-gig where profit is not a primary motivation.  (There are probably a few jobs where a lot of money can be made in your pajamas, but working in pajamas is not the primary objective of the owner!)


## Ideas into Actions

To become useful ideas must be tried (preferably on a small scale at first).  Keep the ones that work; discard the rest.  To that end there are interactive sections in most chapters for you to build your own repository of honest answers, crazy ideas, and progress.


## About Me

I make my living these days by teaching companies how to WOW their customers.  Forty years ago I founded my own boutique tax and consulting firm, sold it after 30 years, and went on to work at a large national firm and a large regional firm.  I now limit my scope to consulting gigs that promise interesting challenges.

I've aggregated the concepts, methods and perspectives I learned over those 40 years in this book.  I haven't 'seen it all' (nobody has) but I've seen enough to teach these basic ideas to those motivated individuals bent on success. 

I always wanted to be a 'young phenom' and now I'm shooting for 'old sage.'  I've gotten the 'old' part down.  The reception this book receives will tell me if I've gotten the 'sage' part down yet.





<br>
<br>

I MIGHT ADD A TOPICS BY CHAPTER SECTION HERE

*   Chapter \@ref(names-values), "Names and values", is a brand new chapter
    that helps you understand the difference between objects and names of
    objects. This helps you more accurately predict when R will make a copy of
    a data structure, and lays important groundwork to understand functional
    programming.

*   Chapter \@ref(vectors-chap), "Vectors" (previously called data structures),
    has been rewritten to focus on vector types like integers, factors, and
    data frames. It contains more details of important S3 vectors (like dates
    and date-times), discusses the data frame variation provided by the
    tibble package [@tibble], and generally reflects my improved understanding
    of vector data types.

*   Chapter \@ref(subsetting), "Subsetting", now distinguishes between `[` and
    `[[` by their intention: `[` extracts many values and `[[` extracts a
    single value (previously they were characterized by whether they "simplified"
    or "preserved"). Section \@ref(subset-single) draws the "train" to help you
    understand how `[[` works with lists, and introduces new functions that
    provide more consistent behavior for out-of-bounds indices.

*   Chapter \@ref(control-flow), "Control flow", is a new chapter: somehow
    I previously forgot about important tools like `if` statements and `for`
    loops!

*   Chapter \@ref(functions), "Functions", has an improved ordering,
    introduces the pipe (`%>%`) as a third way to compose functions (Section
    \@ref(function-composition)), and has considerably improved coverage of
    function forms (Section \@ref(function-forms)).

*   Chapter \@ref(environments), "Environments", has a reorganized treatment of
    special environments (Section \@ref(special-environments)), and a much
    improved discussion of the call stack (Section \@ref(call-stack)).

*   Chapter \@ref(conditions), "Conditions", contains material previously
    in "Exceptions and debugging", and much new content on how R's condition
    system works. It also shows you how to create your own custom condition
    classes (Section \@ref(custom-conditions)).

The chapters following Part I, Foundations, have been re-organised around the three most important programming paradigms in R: functional programming, object-oriented programming, and metaprogramming.

* Functional programming is now more cleanly divided into the three main
  techniques: "Functionals" (Chapter \@ref(functionals)), "Function
  factories" (Chapter \@ref(function-factories)), and "Function operators"
  (Chapter \@ref(function-operators)). I've focused in on ideas that have
  practical applications in data science and reduced the amount of pure theory.

  These chapters now use functions provided by the purrr package [@purrr],
  which allow me to focus more on the underlying ideas and less on the
  incidental details. This led to a considerable simplification of the
  function operators chapter since a major use was to work around the absence
  of ellipses (`...`) in base functionals.

* Object-oriented programming (OOP) now forms a major section of the book with
  completely new chapters on base types (Chapter \@ref(base-types)),
  S3 (Chapter \@ref(s3)), S4 (Chapter \@ref(s4)), R6 (Chapter \@ref(r6)),
  and the tradeoffs between the systems (Chapter \@ref(oo-tradeoffs)).

  These chapters focus on how the different object systems work,
  not how to use them effectively. This is unfortunate, but necessary, because
  many of the technical details are not described elsewhere, and effective use
  of OOP needs a whole book of its own.

* Metaprogramming (previously called "computing on the language") describes the
  suite of tools that you can use to generate code with code. Compared to the
  first edition this material has been substantially expanded and now focuses on
  "tidy evaluation", a set of ideas and theory that make metaprogramming
  safe, well-principled, and accessible to many more R programmers.
  Chapter \@ref(meta-big-picture), "Big picture" coarsely lays out how all
  the pieces fit together; Chapter \@ref(expressions), "Expressions", describes
  the underlying data structures; Chapter \@ref(quasiquotation),
  "Quasiquotation", covers quoting and unquoting; Chapter \@ref(evaluation),
  "Evaluation", explains evaluation of code in special environments; and Chapter
  \@ref(translation), "Translations", pulls all the themes together to show
  how you might translate from one (programming) language to another.

The final section of the book pulls together the chapters on programming techniques: profiling, measuring and improving performance, and Rcpp. The contents are very similar to the first edition, although the organisation is a little different. I have made light updates throughout these chapters particularly to use newer packages (microbenchmark -> bench, lineprof -> profvis), but the majority of the text is the same.



```{r list-packages, echo=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
