Arrow-like characters in Unicode:

    Leftwards Arrow: ← &#x2190;
    Upwards Arrow: ↑ &#x2191;
    Rightwards Arrow: → &#x2192;
    Downwards Arrow: ↓ &#x2193;
    Diagonal Arrow: ↗ &#x2197;
    Diagonal Arrow: ↘ &#x2198;
    Bent Arrow: ↪ &#x21AA;
    Bent Arrow: ↩ &#x21A9;


::: {.rmdcaution}
RED BOX Example of an **.rmdcaution** block.

:::

::: {.rmdimportant}
GREEN BOX Example of an **.rmdimportant** block.

:::

::: {.rmdtip}
BLUE BOX Example of an **.rmdtip** block.

:::

::: {.rmdwarning}
BLUEVIOLET BOX Example of an **.rmdwarning** block.

:::


# Aspirations and Missions 

<blockquote class="my-box" style="text-align: center;">
<p>
    <span style="font-size: 14px">MOTIVATION</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="color: royalblue; font-size: 20px">ASPIRATION</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px">VALUE CREATION</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">COMPETITIVE STRATEGY </span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">MARKET TACTICS</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">PHILOSOPHY</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">OPERATIONS</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">CUSTOMERS</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">SOME LUCK</span>
    <span style="font-size: 24px;">=</span>
    <strong><span style="color: green; font-size: 20px">SUCCESS</span></strong>
  </p>
</blockquote>  



<blockquote class="my-quote">
  <p><strong>"You are never too old to set another goal or to dream a new dream."</strong></p>
  <p class="quote-author">          — attributed to C.S. Lewis</p>
  <p class="quote-description">(renowned British writer and theologian)</p>
</blockquote>


There is no pre-approved list of rules of thumb that will make your company unique and special (despite what many consultants may say).  Otherwise, I would simply list them and tell you to adopt them as fast as possible.

To be an exceptional company you need to create your own rules of thumb that will make you unique.  That thought worries some owners.  They believe that have to 'guess right' the first time or it will spell ruin.   In fact, rules of thumb in a successful company evolve steadily as new ideas are tried on a small scale first.  

The best way I can help you do that with a book is to provide lots of ideas, examples, and concepts that will support your efforts.  Accordingly, there are a lot of words here to help you come up with just a few special words arranged 'just so.'

Read through all the ideas, concepts and examples and create something special for yourself!


## Why Build a Business

You can make a LOT more money with a successful business than as an employee. You can also achieve larger aims by combining skills and resources with others.  That's why you take the risks and work the hours involved.  However, if your cannot transform your personal aspirations into marketplace aspirations you are better off being an employee.

To be useful, marketplace aspirations should describe what your ***business*** must do to accomplish your personal aspirations.  They represent your logic for what the company must become in the marketplace.  Marketing aspirations expressed as personal goals provide no information about what business action is needed.

<span style="color: maroon;">Example:  ***"I want to create great art!"***</span> 


<span style="color: maroon;">Example:  ***"I want to make three times my old salary!"***</span>


<span style="color: maroon;">Example:  ***"I want a vintage corvette!"***</span>


<span style="color: maroon;">Example:  ***"I want to buy the real estate my company sits on for cash in 5 years."***</span>


Another common one...

<span style="color: maroon;">Example:  ***"I just want to practice medicine."***</span>


These are all ***PERSONAL*** aspirations and may be important as motivation for owners, but no one else in the organization or the marketplace will relate to them.  Platitudes are likewise unhelpful...


<span style="color: maroon;">***BUY LOW &#x2192; SELL HIGH &#x2192; MAKE A BILLION DOLLARS***</span>


## From Personal Aspiration to Marketplace Aspiration

To be useful in business personal aspirations must be transformed into marketplace aspirations.  Here are examples using words to describe the transformation...

<span style="color: maroon;">Example:  ***"I want to be famous for my great design...to do that my company must...design and produce super high quality, stylish and distinctive apparel...to do that my company must...become one of the top fashion houses."***</span> 


<span style="color: maroon;">Example:  ***"I want to buy the real estate my company sits on for cash in 5 years...to do that my company must...increase the Average Transaction Value (ATV) to $500.or more...to do that my company must... become the finest veterinary hospital in the eyes of pet owners in the metropolitan area."***</span> 


The last statement in the chain is your marketplace aspiration.  When you transform your personal aspirations into marketplace aspirations you clarify your marketplace ojective..

Marketplace aspirations become Mission Statements which are rules of thumb to provide direction and motivation for the company and its employees, guiding their efforts toward a worthy challenge.

<span style="color: maroon;">Example:  ***"Our mission is...to create the safest playgrounds in the world."***</span> 
<br>
<br>

::: {.rmdimportant}
Observations from the Peanut Gallery...

The more 'noble' the mission sounds the more committed people seem to become.  Strangely, people will follow a 'noble cause' even when it is illogical, impossible, immoral, or irresponsible!

<span style="color: maroon;">Example:  ***"I want to 'save' the planet...to do that I must...fly all over the planet in a polluting jet plane...force others to adopt an unproven technology and risk the economic lives of hundreds of millions of people...to do that I must...create a worldwide governmental movement for 'change'."***</span> 
:::

<br>

## Introducing 'To-Do-That' Diagrams

What these statements have in common is each can be derived by applying what I call a To-Do-That Diagram.  They begin with the desired state and end with the marketplace requirement.  The To-Do-That Diagram expresses the required sequence symbolically, substituting arrows for the words "to do that my company must..." between words or short phrases.

Here are some examples of To-Do-That Diagrams that involve personal as well as business objectives.  With personal objectives each arrow represents the words 'to do that I must...'.  For business each arrow represents the words 'to do that my company must...'

<span style="color: maroon;">***I WANT TO...LIVE HAPPILY EVER AFTER &#x2192; MARRY &#x2192; MEET RESPONSIBLE, FUN PERSON***</span>

<span style="color: maroon;">***I WANT TO...RETIRE A BAZILLONAIRE &#x2192; SELL TO HIGH-TECH GIANT &#x2192; PUSH MY APP INTO MARKETPLACE &#x2192; GET INVESTORS &#x2192; LAUNCH STARTUP &#x2192; INVENT STRING OF COMPELLING NEW APPS***</span>

<span style="color: maroon;">***I WANT TO...DISCOVER A CURE FOR CANCER &#x2192; START A BIO-TECH LAB &#x2192; GET PhD IN BIOPHARACEUTICALS***</span>

Say them out loud.  You get the idea.


Each To-Do-That Diagram represents your logic of how to bring about the desired state.  It expresses one of your rules of thumb.  Serious problems arise when owners consider their 'rules of thumb' as 'laws of nature.'  Later in the book you will learn a method to constantly test your logic to see if it is sound, and still appropriate for conditions.


## Simple is Best

The most powerful marketplace aspiration statements are short, and memorable.

<span style="color: maroon;">For example:    "We want to.be very successful...to do that the company must...be the market of choice for dairy products and produce in the tri-state area...to do that the company must...create delighted customers."</span> 

This becomes...<span style="color: maroon;">"Our Mission is to Create Delighted Customers"</span>

This type of marketplace aspiration guided Stew Leonard's Dairy Store when they first opened, and still guides the $700 million dollar business they've become.

Simple, straightforward, and plain-spoken.  Management's job is then to create a system capable of delivering what the mission statement promises.
<br>
<br>


::: {.rmdimportant}
<b><i><span style="color: red; font-size: 18px;">Dan Swart's "Gobbledygook Rule of Thumb":</span>

If you haven't used a word in your family or casual conversations in the last month, <b><i><span style="color: red; font-size: 18px;">don't use it in your business communications!<i><b></span>
:::
<br>


::: {.rmdwarning}
Esoteric statements made of corporate 'newspeak' are incomprehensible and useless as a guide for action.  They make me want to 'circle back', 'parachute in' and then 'lean in' so I become 'passionate' about 'unpacking' more 'bandwidth' for the 'stakeholders' who have 'pinged' me about 'pivoting' during my 'deep dive' as a 'change agent' with a 'holistic approach' that gets me to 'think outside the box' and 'push back' about the 'pain points' I feel are not 'robust' or 'actionable' 'outcomes'!

Instead, I will visit your business, observe the work in action and meet with you next week on Friday at 2 pm to discuss my observations.  We can meet by phone, live-stream, or in person to discuss what might be done next.  I will then call you to confirm date, time and your choice of venue.

:::

<br>

## 'To-Do-That' Elements are Interdependent

Although the order of the elements in the diagrams matter as a logical device, they are NOT independent of each other.  All elements affect each other and must be coordinated as a system.  An 'improvement' in one element may, in fact, degrade the performance of the total chain.


## Theory and You

Business people usually HATE the word 'theory'.  It sounds out of touch with the 'practical' world we live in.  The truth is, ALL organizations operate based on theory.  Management in ALL forms is prediction:  'if we do this, that will happen.'  When we choose to take action, not to take action, or discontinue an action we are predicting the future results of that decision.  Nothing could be more practical than that!

All rules of thumb and To-Do-That Diagrams are theories.  Because people, marketplaces, consumers, political environments, technologies, etc. cannot be predicted with 100% accuracy, and because they change over time, we cannot ***guarantee*** any particular outcome.  So we put our best work out into the world and see if we can make a difference.

Every day our business (and our personal lives) produces information about how our To-Do-That Diagrams are working.  If we are receptive to new information, and make an effort to collect it, the To-Do-That Diagram helps us learn which elements of the chain reaction are helping, and which are not.  

Very successful companies understand their To-Do-That Diagrams, test their assumptions, and constantly look for ways to improve the effectiveness of the chain ***taken as a whole.***
<br>

## Ideas to Actions


::: {.rmdimportant}

**EXERCISE 2-1**

<span style="color: red;">**Interactive Online Version:**</span>   [https://danswart.shinyapps.io/ryb-exercises-2-1/]

Ideas take form when you commit them to writing.  Write your answers to the following:


1. **Draft your personal aspiration(s).  They don't have to be poetry, or socially conscious, or profound...just honest.**
<br>
<br>
<br>

1. **Transform each personal aspiration to a marketing aspiration using a To-Do-That Diagram.  Say them out load.  It may seem silly at first, but they are POWERFUL.**
<br>
<br>
<br>

1. **Draft a Mission Statement from the last phrase of your completed To-Do-That Diagram.  If you cannot derive a good Mission Statement from the last phrase, add another phrase until you can.**
<br>
<br>
<br>

:::


