

# **Customers and Value** 

<blockquote class="my-box" style="text-align: center;">
<p>
    <span style="font-size: 14px">MOTIVATION</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px">ASPIRATION</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="color: royalblue; font-size: 20px">CREATE VALUE</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">COMPETITIVE STRATEGY </span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">MARKET TACTICS</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">PHILOSOPHY</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">OPERATIONS</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">CUSTOMERS</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">SOME LUCK</span>
    <span style="font-size: 24px;">=</span>
    <strong><span style="color: green; font-size: 20px">SUCCESS</span></strong>
  </p>
</blockquote>  

<blockquote class="my-quote">
  <p><strong>"There are only two ways to create value...<br><br>
  Figure out what you can <u>make</u>, and find really clever ways to make people want it,<br><br>
  <span class="ml7">OR</span><br><br>
  <span class="ml4">Figure out what people <u>want</u>, and find really clever ways to provide it."</span></strong></p>
  <p class="quote-author">          — Rory Sutherland</p>
  <p class="quote-description">(Vice Chairman of Ogilvy UK)</p>
</blockquote>



## **Creating Value in the Marketplace**


There is only one definition of value that matters; and it is provided solely by the consumer.

If you don't adopt that as a key 'rule of thumb' you will have a difficult time in business.  It's often the main difference between owners and employees. 

It is gospel -- mantra.

You are correct.  Many consumers are not rational.  And, yes, sometimes they ARE wrong.  The marketplace will punish you severely if your business operates under those two correct, but destructive assumptions.

Many extraordinary and useful innovations have been rejected by the marketplace.  People do not necessarily want a better mousetrap!

Now that you know WHY you can be of value to others, you have to figure out HOW you can be of value to others.  There are two fundamentally different approaches to creating and delivering value, often referred to as "product-driven" and "customer-driven" strategies.

I call product-driven strategy <span class="f3 darkgreen"> 'Make, then Sell'</span> strategy.

Customer-driven strategy I call <span class="f3 darkgreen">'Listen, then Provide'</span> strategy.

Those two labels seem much more descriptive of the action to be taken for each.

The predominant strategy employed since mass-production became possible is <span class="f4 darkgreen"> 'Make, then Sell'</span>.  It is the conventional way people approach the marketplace.  They begin with a skill set, or a product idea, then try to think of clever phrases, logos, and networking schemes to convince buyers they're the solution to their problems.  It's a task of gaining attention, then persuasion. Companies seeking outside investors are commonly expected to use the <span class="f4 darkgreen"> 'Make, then Sell'</span> strategy.  You can make money this way, but the competitive landscape is fierce and unforgiving.

The <span class="f4 darkgreen">'Listen, then Provide'</span> strategy has a built-in competitive advantage - it is unconventional.  The <span class="f4 darkgreen">'Listen, then Provide'</span> strategy is appropriate and available to any company, but it remains the exception.  


Every company in the marketplace employs one of these two strategies in one form or another.  Many companies (particularly service companies) employ the <span class="f4 darkgreen"> 'Make, then Sell'</span> strategy but perform poorly with the 'Sell' element of the equation. They open up shop and hope that word of mouth will spontaneously occur through just the force of their technical skills or personality.  This is unfortunate for them, but fortunate for their competition!

This book emphasizes the great competitive advantages of the <span class="f4 darkgreen">'Listen, then Provide'</span> strategy.
<br>


## **Product-Driven Strategy (<span class="f4 darkgreen">'Make, then Sell'</span>)**


**Focus**

The primary focus of this strategy is to create a product or service based on the company's idea of what a customer should value - not necessarily on customers' expressed needs or desires. The American auto industry is an excellent example of this strategy.  Features deemed important by top executives find expression in each year's models.  Silicon Valley hi-tech companies engage in intense competition over feature-rich hardware and software 'solutions' searching for problems to solve.  Heavy investment in research and development is the primary mechanism for differentiation.  Competing 'solutions' reach the marketplace rapidly.
<br>


**Push Marketing**

This approach relies heavily on pushing the product or service into the market and trying to convince potential customers that they need it, or should want it. Watch television or go online for two minutes and you will be inundated with companies using this approach.  Marketing and advertising play a predominant role in showcasing the product's features and hoped-for benefits. 
<br>


**Risk of Mismatch**

If the product does not align with what customers actually want or need, it leads to market rejection and financial loss for the company. This strategy assumes that customers will adapt to the product rather than the product adapting to the customer.  In this environment corporate executives often rise and fall based on lucky timing rather than market savvy.
<br>


## **Customer-Driven Strategy (<span class="f4 darkgreen">'Listen, then Provide'</span>)**


**Assessing Customer Needs**

A <span class="f4 darkgreen">'Listen, then Provide'</span> strategy begins with understanding customer needs, desires, and point of rejection of the good or service.  Market research, customer feedback, and data analysis are used to identify gaps and opportunities.  The deeper your understanding and empathy for the customer point of view, the greater your ability to create and/or provide value.
<br>

**Pull Marketing**

With this approach the goal is to create products or services addressing customers' expressed needs and desires.  It relies on "pull marketing," where customers can 'pull' value whenever they feel the need.  It permits high customization and can cope with the high variation in market pressures.  This 'just-in-time' methodology stands in stark contrast to companies that produce based on physical capacity or to minimize accounting-based cost estimates.
<br>

**Reduced Risk**

This strategy is generally considered less risky because it starts with a validated market need. It is more likely to lead to product-market fit and customer satisfaction.
<br>


## **Other Considerations**


**Market Dynamics**

The choice between these strategies will depend on the nature of the market and personality of the owner. In rapidly changing industries with emerging technologies, a product-driven approach may be necessary to produce the innovation needed to create new markets. In more mature markets, a <span class="f4 darkgreen">'Listen, then Provide'</span> approach is very much more likely to be effective.
<br>


**Customer-Centric**

<span class="f4 darkgreen">'Listen, then Provide'</span> strategies place emphasis on customer-centric behavior from everyone in the company.  This translates to solid customer loyalty and long-term success.
<br>


## **Hybrid Approach**

This is a VERY strong strategy.  You can anticipate future needs your customers might face as well as their current ones.  Buggywhip makers had loyal customers...until the automobile came along.  Carburetor manufacturers year after year made better and better carburetors.  They had many happy customers.  Then came the fuel injector.  They did not monitor currently developing options nor did they include the future in their customer service plans. The market disappeared.

A hybrid approach is a way to be ahead of the game for your customers.

For example, you may use a <span class="f4 darkgreen">'Listen, then Provide'</span> approach to identify current needs and apply a <span class="f4 darkgreen"> 'Make, then Sell'</span> approach to anticipate and create innovative solutions that solve customer problems of the future.  No customer ever asked for a transistor, photocopy machine, electric car, or desktop publishing software.  Suppliers looking to the future understood the potential for such items to improve the material well-being of consumers.

Ultimately, the success of either strategy depends on your ability to provide value to customers. In practice, companies often need to strike a balance between these two approaches, especially in competitive and evolving markets. Continuous feedback loops with customers and a willingness to change are crucial for long-term success.


## The Small Business


Small business owners, unlike startups seeking external investors, often face different considerations when choosing between <span class="f4 darkgreen"> 'Make, then Sell'</span> and <span class="f4 darkgreen">'Listen, then Provide'</span> strategies. Here are some key factors small business owners should consider:
<br>


**Existing Customer Base**

Small companies may already have an established customer base. Understanding the preferences, needs, and desires of these existing customers is crucial. A <span class="f4 darkgreen">'Listen, then Provide'</span> approach creates loyal customers and the ability to expand (or discontinue) offerings based on their input.
<br>


**Resource Constraints**

Small companies typically have limited resources, including financial resources and manpower. They must consider the resources needed for product development, marketing, and operations for a successful product-driven approach. A <span class="f4 darkgreen">'Listen, then Provide'</span> approach is more cost-effective initially, and in the long run.
<br>


**Customer Relationships**

Strong customer relationships are particularly important for small companies who are typically reliant on strong repeat business.  Maintaining and nurturing these relationships provides valuable insights and word-of-mouth referrals.
<br>


**Consistency with Values**

Customer-driven strategies often align better with small business values and aspirations.  Customers often appreciate companies that genuinely care about their needs and preferences.
<br>


**Financial Stability**

Honestly assess the financial stability of your business. If your business is financially stable, you may have more flexibility to invest in product development. However, if resources are limited, a <span class="f4 darkgreen">'Listen, then Provide'</span> approach may be more practical.
<br>


Small business owners should carefully weigh these factors, taking into account their unique circumstances and goals. Flexibility and adaptability are also key as the business landscape evolves. It's often beneficial to start with a <span class="f4 darkgreen">'Listen, then Provide'</span> approach to establish a strong customer base and then consider product-driven innovations as the business grows.


## Choosing Your Preferred Strategy

**Authenticity Matters**

You cannot succeed in business if you try to be someone you're not.  Each of the two strategies will require different attitudes and behaviors from you.  If a strategy demands actions and decisions that are in conflict with your basic personality or values you will not succeed in implementing that strategy. That is setting yourself up for failure!
<br>

Be true to yourself. Understand your values, beliefs, and strengths. Authenticity builds trust with customers, employees, and partners. People are drawn to authenticity because it's relatable and trustworthy.
<br>


**Know Your Niche**

Identify a niche or market segment that aligns with your authentic self. Focus on areas where you have genuine interest and expertise. Will your chosen strategy work well in your niche or market segment? This also makes it easier to stay passionate about what you're doing.
<br>


**Build Relationships**

The <span class="f4 darkgreen">'Listen, then Provide'</span> strategy relies on very strong customer relationships. Can you be sincere and build strong connections with clients, colleagues, and mentors? Authentic relationships will lead to more collaboration and opportunities to contribute value.
<br>


**Set Clear Boundaries**

When choosing a strategy understand your limits and boundaries. Don't take on a strategy that doesn't align with your values or goals. Learning to say no when necessary is a sign of authenticity.
<br>


**Appreciate Your Uniqueness**

Pick a strategy that can leverage your uniqueness as a competitive advantage. What sets you apart will be a selling point for your business. Embrace your quirks and idiosyncrasies!
<br>


## Final Thoughts

Before moving on to implementation, keep these thoughts in mind...
<br>

**Continuous Learning**

Stay curious and committed to learning and personal growth. Embrace change and adapt to new situations while staying true to your core values.  It is a hallmark of authenticity.
<br>

**Honesty and Transparency**

Be open and honest in your business dealings. Transparency builds trust with customers and partners. Acknowledge mistakes and take responsibility when things go wrong.
<br>

**Define Success on Your Terms**

Success means different things to different people. Define what success means to you personally, beyond financial metrics. This might include work-life balance, personal growth, or making a positive impact on your community.
<br>

**Seek Guidance**

Consider working with a mentor or coach who can help you navigate the challenges of business while staying true to yourself. They can provide valuable insights and support.
<br>

**Stay Mindful**

Regularly reflect on your values, goals, and the direction of your business. Mindfulness practices will help you stay connected to your authentic self.
<br>

**Appreciate the Small Wins**

Acknowledge and be grateful for your achievements, no matter how small they may seem. Acknowledging progress boosts confidence and motivation.
<br>

**Surround Yourself with Support**

Build a support network of friends, family, and peers who understand and appreciate your authentic self. They will provide encouragement during tough times.
<br>

Staying true to yourself in business will lead to a more fulfilling and successful entrepreneurial journey.


::: {.rmdtip}
**The remainder of the book assumes you have chosen the <span class="f4 darkgreen">'Listen, then Provide'</span> - Customer-Driven strategy**

:::
