# (PART\*) Part II - PLANNING TO WIN {-} 

Arrow-like characters in Unicode:

    Leftwards Arrow: ← &#x2190;
    Upwards Arrow: ↑ &#x2191;
    Rightwards Arrow: → &#x2192;
    Downwards Arrow: ↓ &#x2193;
    Diagonal Arrow: ↗ &#x2197;
    Diagonal Arrow: ↘ &#x2198;
    Bent Arrow: ↪ &#x21AA;
    Bent Arrow: ↩ &#x21A9;


::: {.rmdcaution}
RED BOX Example of an **.rmdcaution** block.

:::

::: {.rmdimportant}
GREEN BOX Example of an **.rmdimportant** block.

:::

::: {.rmdtip}
BLUE BOX Example of an **.rmdtip** block.

:::

::: {.rmdwarning}
BLUEVIOLET BOX Example of an **.rmdwarning** block.

:::


# The Role of Competitive Strategy 

<blockquote class="my-box" style="text-align: center;">
<p>
    <span style="font-size: 14px">MOTIVATION</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px">ASPIRATION</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px">CREATE VALUE</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">COMPETITIVE STRATEGY </span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">MARKET TACTICS</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">PHILOSOPHY</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">OPERATIONS</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">CUSTOMERS</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">SOME LUCK</span>
    <span style="font-size: 24px;">=</span>
    <strong><span style="color: green; font-size: 20px">SUCCESS</span></strong>
  </p>
</blockquote>  


<blockquote class="my-quote">
  <p><strong>"To succeed in the market, you need to be the best at something, to be first, the cheapest or the most premium, or just different."</strong></p>
  <p class="quote-author">      — attributed to Seth Godin</p>
  <p class="quote-description">(well-known marketing author and speaker)</p>
</blockquote>



Discussing competitive strategy is difficult for some people.  Modern media and most of academia depict the marketplace in very negative ways and people don't like to think of what they do as a 'competition.'  They don't want to be perceived  as too clever, or caniving, cutthroat, mean or worst of all...greedy.  At some level they worry that thinking in terms of competition will dehumanize themselves and their competitors.  They want to be a 'good person.'

It's harmful to use the media and academia to evaluate the content of your character.  Everyone can build a business consistent with who they really are.  There's room for eveyone.

So, shrug off those negative perceptions and adopt a plan to create more value for customers than your competitors.  If you aren't competitive, or don't want to be competitive, you should remain an employee.

Just to survive business owners MUST figure out ways to deploy resources in ways that create an advantage that is difficult to duplicate.  Will you be first, cheapest, the most premium, or just different?

Competitive strategy is more important than you think.  Can you name your marketplace goals, be it market leadership, innovation, customer service excellence, or cost leadership? 

When you complete this chapter you should have a draft competitive strategy in hand.


## Marketplace Scope and Your Value Proposition

Michael Porter developed a very convenient way to identify your competitors and the ways they are trying to provide superior value to customers better than you do. (see https://en.wikipedia.org/wiki/Michael_Porter)

According to Porter, there are two broad categories of competition:  <span style="color: blue;">**Cost Leadership**</span> and <span style="color: blue;">**Differentiation**</span>.

<span style="color: blue;">**Cost Leadership**</span> involves competing to offer products and services at the lowest cost for a perceived level of quality (cheap, but worth it).

Example: Walmart provides goods at lower prices than its competitors.
By what method?  Through efficient supply chain management and large-scale operations.


<span style="color: blue;">**Differentiation**</span> involves competing by offering unique products or services on dimensions that matter to the customer (expensive, but worth it).

Example: Apple differentiates its products through innovative design, high-quality materials, and excellent customer service.
<br><br>


Within those two broad categories you can specialize into niche markets.

<span style="color: blue;">Niche Focus</span> involves competing as either the low-cost provider or by being different, but in a specific market niche. Not industry-wide; just the amongst the other niche competitors.  
<br>

Example: Tesla focuses on the niche of electric vehicles and differentiates itself through cutting-edge technology, superior performance and mindfulness of the environment.  It is now quite a status symbol in America.

Example: Spirit Airlines operates as a low-cost carrier focused on budget-conscious travelers.
<br><br>

Whichever strategy you choose, it's not just about being better; it's about being *DIFFERENT* in a way that is important to consumers (the marketplace).

Do you have unique strengths, such as technological expertise, customer service excellence, or efficient supply chain management?  If not, you must develop them.  Once you can differentiate yourself in the market, offer something that competitors cannot easily replicate.



Again, a diagram will help.


<!-- Style-On-the-Spot to Include Text Color and Background in Pipe Table -->
<!-- The swart.css file defines the bg-background colors, but not the text colors. -->


<style>
  .cornflowerblue-bg {
    background-color: cornflowerblue;
    color: white;
  }

  .firebrick-bg {
    background-color: firebrick;
    color: white;
  }

  .blueviolet-bg {
    background-color: blueviolet;
    color: white;
  }

  .forestgreen-bg {
    background-color: forestgreen;
    color: white;
  }

</style>

| | Larger Scope | Smaller Scope|
|:------------------------------|:-------------------------------:|:--------------------------------:|
|<br>Value Proposition      | <span class="cornflowerblue-bg">&nbsp;&nbsp;&nbsp;Industry-Wide&nbsp;&nbsp;&nbsp;<br><span class="firebrick-bg">&nbsp;&nbsp;&nbsp;Cost Leader&nbsp;&nbsp;&nbsp;</span><br><br> | <span class="blueviolet-bg">&nbsp;&nbsp;&nbsp;Niche-Market&nbsp;&nbsp;&nbsp;<br><span class="firebrick-bg">&nbsp;&nbsp;&nbsp;Cost Leader&nbsp;&nbsp;&nbsp;</span> <br><br>|
| <br>Value Proposition | <span class="cornflowerblue-bg">&nbsp;&nbsp;&nbsp;Industry-Wide&nbsp;&nbsp;&nbsp;<br><span class="forestgreen-bg"> &nbsp;&nbsp;&nbsp;Differentiator&nbsp;&nbsp;&nbsp;</span><br><br> | <span class="blueviolet-bg">&nbsp;&nbsp;&nbsp;Niche-Market&nbsp;&nbsp;&nbsp;<br><span class="forestgreen-bg">&nbsp;&nbsp;&nbsp; Differentiator&nbsp;&nbsp;&nbsp;</span> |

:  "Michal Porter's Four Competitive Strategies Matrix".


## More Competitive Strategy Examples
<br>

<span class="cornflowerblue-bg">Industry-Wide</span> <span class="firebrick-bg"> Cost Leader</span>

- Southwest Airlines

- Target

- McDonald’s
<br><br>

<span class="cornflowerblue-bg">Industry-Wide</span> <span class="forestgreen-bg">Differentiator</span>

- Lexus (reliability)

- Volvo (safety)

- Harley-Davidson (Americana)
<br><br>


<span class="blueviolet-bg">Niche-Market</span> <span class="firebrick-bg"> Cost Leader</span>

- Galaxy Furniture (aka 'Mattress Mack' in Houston, TX USA)

- Dollar Tree

- Stew Leonard's (grocery stores in the New York, NY USA suburbs)

<br><br>

<span class="blueviolet-bg">Niche-Market</span> <span class="forestgreen-bg"> Differentiator</span>

- Rolls Royce (exclusivity)

- Buc-ee's (biggest, cleanest, most fun gas station anywhere)

- Whataburger (freshest, build-your-own)

<br>

::: {.rmdcaution}
Warning:  Hopping Around from one strategy to another is a 'Company Killer'!  DON'T DO IT.
:::
<br>



## Ideas to Actions

::: {.rmdimportant}


**EXERCISE 2-1**

1. Draw a circle around your chosen marketplace scope and value proposition (then stick to it!)
<br><br>


<style>
  .cornflowerblue-bg {
    background-color: cornflowerblue;
    color: white;
  }

  .firebrick-bg {
    background-color: firebrick;
    color: white;
  }

  .blueviolet-bg {
    background-color: blueviolet;
    color: white;
  }

  .forestgreen-bg {
    background-color: forestgreen;
    color: white;
  }

</style>

| | Large Scope | Smaller Scope|
|:------------------------------|:-------------------------------:|:--------------------------------:|
|<br>Value Proposition      | <span class="cornflowerblue-bg">&nbsp;&nbsp;&nbsp;Industry-Wide&nbsp;&nbsp;&nbsp;<br><span class="firebrick-bg">&nbsp;&nbsp;&nbsp;Cost Leader&nbsp;&nbsp;&nbsp;</span><br><br> | <span class="blueviolet-bg">&nbsp;&nbsp;&nbsp;Niche-Market&nbsp;&nbsp;&nbsp;<br><span class="firebrick-bg">&nbsp;&nbsp;&nbsp;Cost Leader&nbsp;&nbsp;&nbsp;</span> <br><br>|
| <br>Value Proposition | <span class="cornflowerblue-bg">&nbsp;&nbsp;&nbsp;Industry-Wide&nbsp;&nbsp;&nbsp;<br><span class="forestgreen-bg"> &nbsp;&nbsp;&nbsp;Differentiator&nbsp;&nbsp;&nbsp;</span><br><br> | <span class="blueviolet-bg">&nbsp;&nbsp;&nbsp;Niche-Market&nbsp;&nbsp;&nbsp;<br><span class="forestgreen-bg">&nbsp;&nbsp;&nbsp; Differentiator&nbsp;&nbsp;&nbsp;</span> |

:  "Michal Porter's Four Competitive Strategies Matrix".

**EXERCISE 2-2**

2. This is a fun one; classifying other companies...Write-in two more examples of each of the four marketplace strategies:<br><br>

<span class="cornflowerblue-bg">Industry-Wide</span> <span class="firebrick-bg"> Cost Leader</span>

- Southwest Airlines

- Wal-Mart

- McDonald’s

- [?]

- [?]


<span class="cornflowerblue-bg">Industry-Wide</span> <span class="forestgreen-bg">Differentiator</span>

- Apple

- Tesla

- Harley-Davidson

- [?]

- [?]


<span class="blueviolet-bg">Niche-Market</span> <span class="firebrick-bg"> Cost Leader</span>

- Galaxy Furniture (aka 'Mattress Mack' in Houston)

- Dollar Tree

- Stew Leonard's (grocery stores in the New York suburbs)

- [?]

- [?] 


<span class="blueviolet-bg">Niche-Market</span> <span class="forestgreen-bg"> Differentiator</span>

- Rolls Royce

- Buc-ee's

- Whataburger

- [?]

- [?] 


:::





## No Guarantees!

No one can know in advance if any particular competitive strategy will be effective.  You must have the courage to try it and see what happens.  Improve it until it is both innovative and repeatable.  Accept that any strategy is a minature experment.  Force it to evolve based on market feedback and changing conditions. 

For instance, you might choose to develop a proprietary technology that should set your products apart, or you might cultivate a unique brand identity that you hope resonates deeply with a specific customer segment. 

Use complexity, unique resources, company culture, or brand loyalty to your advantage to make it challenging for competitors to duplicate quickly or easily.


## Conclusion

Achieving an advantageous competitive position requires a clear vision of the target market, an understanding of what customers value most, and an unrelenting focus on delivering that value. The strategic position you choose will inform decisions across the company, from product development to marketing, sales, and beyond. 

competitive strategy is the art and science of matching the company's unique strengths to the marketplace in a way that creates exceptional value for customers and challenges for competitors. 

It’s not merely about competing for market share; it's about carving out a unique space in the marketplace where the company's strengths align perfectly with customer needs.

Understand where you fit in the competitive landscape, how you can deliver unique value, and executing your plan in a way that's both effective and hard to replicate. The success of this strategy is measured not just in immediate gains but in the long-term profitability of the company.


<br><br><br>


## ***** POSSSIBLE WORKSHOPS *****
 


- Understand Your Industry: Use Porter's Five Forces analysis.

- Understand Your Company: Conduct a SWOT analysis.

- Understand Customer Needs and Desires: Conduct a Client Advisory Board and other customer research.

Implementing Your Competitive Strategy

Once you've chosen your strategy:

- Communicate the Strategy: Everyone in the team should understand the strategy.

- Align Operations with the Strategy: Operations should reflect your strategy and be made capable of delivering value in customer terms.

- Monitor Capability to Deliver Value: Regularly review performance to ensure effectiveness, not efficiency.


=========================

FORMULATION 1

If you seek solutions that create customer value where everyone comes out better...customers, employees, suppliers, even competitors when possible.

GOAL (MISSION) &#x2192; CREATE DELIGHTED CUSTOMERS<br>
BY WHAT METHOD &#x2192; THROUGH CONTINUOUS IMPROVEMENT AND RESPECT FOR PEOPLE

- (this formulation produces the highest quality at the lowest total cost, highest productivity, and highest loyalty)


FORMULATION 2

If you seek solutions that create customer value where some parties win and some don't.

GOAL (MISSION) &#x2192; CREATE ACCEPTABLE MIX OF SATISFIED AND UNSATISFIED CUSTOMERS<br>
BY WHAT METHOD? &#x2192; SEEK HIGHEST PROFIT MARGIN PER UNIT/JOB POSSIBLE; ACCEPT SOLUTIONS WHERE SOME PARTIES WIN, AND SOME LOSE WITH LITTLE REGARD TO CUSTOMER RETENTION

(this formulation will produce lower quality at higher total cost and lower productivity)


FORMULATION 3

If you seek solutions that create customer value at the lowest possible cost of materials, labor, and administration.

MISSION &#x2192; CREATE CUSTOMERS WHO WILL TAKE WHAT WE GIVE THEM<br>
BY WHAT METHOD? &#x2192; PRODUCE AT LOWEST INITIAL COST PER UNIT, WITHOUT REGARD TO TOTAL COST OR CUSTOMER RETENTION

(this formulation will produce lowest quality at highest total cost and lowest productivity)



Here's an example...



