
Arrow-like characters in Unicode:

    Leftwards Arrow: ← &#x2190;
    Upwards Arrow: ↑ &#x2191;
    Rightwards Arrow: → &#x2192;
    Downwards Arrow: ↓ &#x2193;
    Diagonal Arrow: ↗ &#x2197;
    Diagonal Arrow: ↘ &#x2198;
    Bent Arrow: ↪ &#x21AA;
    Bent Arrow: ↩ &#x21A9;


::: {.rmdcaution}
RED BOX Example of an **.rmdcaution** block.

:::

::: {.rmdimportant}
GREEN BOX Example of an **.rmdimportant** block.

:::

::: {.rmdtip}
BLUE BOX Example of an **.rmdtip** block.

:::

::: {.rmdwarning}
BLUE VIOLET BOX Example of an **.rmdwarning** block.

:::



# The Role of Market Tactics

<blockquote class="my-box" style="text-align: center;">
<p>
    <span style="font-size: 14px">MOTIVATION</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px">ASPIRATION</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px">CREATE VALUE</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">COMPETITIVE STRATEGY </span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="color: royalblue; font-size: 20px;">MARKET TACTICS</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">PHILOSOPHY</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">OPERATIONS</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">CUSTOMERS</span>
    <span style="font-size: 24px;">&plus;</span>
    <span style="font-size: 14px;">SOME LUCK</span>
    <span style="font-size: 24px;">=</span>
    <strong><span style="color: green; font-size: 20px">SUCCESS</span></strong>
  </p>
</blockquote>  


<blockquote class="my-quote">
  <p><strong>"A numerical goal alone accomplishes nothing.  What counts is the method -- by what method?"</strong></p>
  <p class="quote-author">    — W. Edwards Deming</p>
  <p class="quote-description">(*The New Economics for Industry, Government, Education (p. 41). Kindle Edition.*)</p>
</blockquote>


Strategy is abstract.  It is a result that cannot be controlled directly.  It outlines the long-term direction and objectives of the business.  Tactics are about the here and now - the specific methods and actions taken to achieve the strategic goals.  They are the operational elements that bring a marketing strategy to life, translating high-level plans into operational tasks.

Tactics are inherently detail-oriented and focus on immediate or near-term actions that contribute to larger strategic objectives. For example, if a company's strategy is to become the market leader in a specific sector, its tactics might include aggressive marketing campaigns, competitive pricing strategies, or partnerships with key players in the industry. These tactical moves are designed to build market share, enhance brand recognition, or create customer loyalty - all of which serve the broader strategic goal of market leadership.

Effective marketing tactics are flexibile and adaptable. Unlike strategy, which is more stable and long-term, tactics can and should be adjusted frequently based on market feedback and changing conditions.  This form of agility allows you to respond quickly to new opportunities, competitive pressures, or shifts in consumer preference. For instance, in response to a competitor's product launch, a company might tactically ramp up promotional activities or introduce product enhancements to maintain its competitive edge.

These is no end to the theoretical analysis of market strategy and tactics.  You can dig as deep as you like.  The goal of this book is to create action, as well as thought.  So, let's look at things to do.


::: {.rmdwarning}

Here's the Thing...

<span class="f4 red">NOBODY</span> knows in advance what exact combination of tactics will give you the competitive advantage you need.  <span class="f4 red">NOBODY.</span>

The 'solution' that worked for one organization may not work at all for you.  Every company is different in important ways; even within the same industry.  If you weren't different in important ways you could never gain an advantage in the first place.

Solutions come from a constant process of discovery.

Sometimes tactics that seem obvious will be dead ends and sometimes ideas that sound crazy at first work perfectly.  Ideas can be 'Simple, obvious, and WRONG!'  That's why ideas that sound like solutions are so seductive.

The best combinations of tactics EMERGE if you are actively engaged in the discovery process.

Prepare yourself now.  There are NO RECIPES except those you discover yourself.  Emergence can be a messy, frustrating process, but it's how real-world advantage comes about.

Companies struggle and fail when management loses the enthusiasm and patience for discovery.
:::


Dr. Deming cautioned repeatedly not to establish goals without including a method to achieve them.  Market Tactics answers the all-important question: "By what method?"

<span style="color: red;">Example:</span> Walmart provides goods at lower prices than its competitors.

<span style="color: blueviolet;">By what method?</span>  Efficient supply chain management and large-scale operations.


To-Do-That diagrams are perfect for answering the 'by what method?' question.



Typical tactics include...

- Quality levels
- Pricing decisions
- Cost structures
- Service levels
- Consumer sentiment
- Production constraints
- Customer emotions
- Employee engagement
<br><br>


These factors, and many more, are potential ways to outperform your competitors in the eyes of customers.  A strong competitive advantage does not just 'happen.'  It comes from purposeful engagment with your materials, methods, equipment, customers, employees and suppliers to find unique or creative combinations that make customers say 'WOW!'  It is a process of discovery and sometimes an innovation in any one of them can completely disrupt the market in your favor.

One thing we know for certain is conventional thinking will NOT bring you what you need or want.  'WOW!' has never come from conventional thinking.



## 'How-To' Gain and Hold Advantages


Here is an example:


It involves continuous communication and coordination across various departments within the organization, ensuring that everyone is allowed to and does work towards the same strategic objectives and that tactical decisions are made within the context of the larger strategic plan.
